service: flask-app

provider:
  name: aws
  runtime: python3.6
  stage: dev

# puglins necessarios para 1:empacotar nosso requirements automatimente no nosso deploy
# 2: comunicacao no serverless com o wsgi
plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false


functions:
  app:
    handler: wsgi.app
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      #deixam a funcao de mapeamento de rotas para a minha aplicacao(flask)
